version: '3.8'

services:
  client:
    container_name: dcpoker-client
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"  # Для HTTPS
    volumes:
      - ./ssl:/etc/nginx/ssl  # Для SSL-сертификатов
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - dcpoker-network
    environment:
      - NGINX_HOST=localhost  # Имя хоста для Nginx

  server:
    container_name: dcpoker-server
    build:
      context: ./server
      dockerfile: Dockerfile
    # Не публикуем порт 3001 наружу, доступ только через Nginx
    # ports:
    #  - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost,http://eg5or.ru,https://eg5or.ru}
      - MONGODB_URI=mongodb://mongodb:27017/dcpoker
      - JWT_SECRET=${JWT_SECRET:-supersecret_jwt_key_change_in_production}
      - JWT_EXPIRES_IN=7d
    depends_on:
      - mongodb
    restart: unless-stopped
    init: true
    networks:
      - dcpoker-network

  mongodb:
    container_name: dcpoker-mongodb
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb  # Для конфигурации MongoDB
    # Не публикуем порт MongoDB наружу для безопасности
    # ports:
    #  - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=dcpoker
    command: ["--bind_ip", "0.0.0.0"]
    networks:
      - dcpoker-network

volumes:
  mongo_data:
    name: dcpoker_mongodb_data
  mongo_config:
    name: dcpoker_mongodb_config
    
networks:
  dcpoker-network:
    name: dcpoker-network 